# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsuzuki" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "7ad13e361f7bb38de7660d09d0aead870e6c9aaa5f3d2046b6af12811c37497d"
      url "https://github.com/EmoFa/tsuzuki/releases/download/v#{version}/tsuzuki_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "415e7d7a5b17b311c8a3fed64ca38de53c77c34dc76669c904261ec780bf3ce0"
      url "https://github.com/EmoFa/tsuzuki/releases/download/v#{version}/tsuzuki_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "65032cb7e714b096636afe7acec4de7d64858dac3aa787f7eeb7a36fd10c528a"
      url "https://github.com/EmoFa/tsuzuki/releases/download/v#{version}/tsuzuki_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e6c6ac377ece06d21b8f0bc9fcc9b732b044f292a16e185c222e1acfa216ced5"
      url "https://github.com/EmoFa/tsuzuki/releases/download/v#{version}/tsuzuki_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tsuzuki"
  desc "Watch anime from your terminal in mpv, with AniList tracking"
  homepage "https://github.com/EmoFa/tsuzuki"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "tsuzuki"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsuzuki"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Anikoto and bot-protection checks need Chrome or Chromium.
    Run `tsuzuki doctor` to check your setup.
  EOS
end
