# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsuzuki" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "ae24c8cef484b7e7c974baaaba3a3b99188bcbd0da60bc7023c06e97a9f3bf73"
      url "https://github.com/EmoFa/tsuzuki/releases/download/v#{version}/tsuzuki_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7501709f91f8eb1ee9285313880f8e0988546773da2b8f92887e0ced4188ca58"
      url "https://github.com/EmoFa/tsuzuki/releases/download/v#{version}/tsuzuki_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bf37908b004b7a2e55feb5c0edbe3bf7de31d02fac421c698ff91dc12051766b"
      url "https://github.com/EmoFa/tsuzuki/releases/download/v#{version}/tsuzuki_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f23b35cff1e8dae198953feea9b59c63ebec2657c725a004f2bd67128b085109"
      url "https://github.com/EmoFa/tsuzuki/releases/download/v#{version}/tsuzuki_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tsuzuki"
  desc "Watch anime from your terminal in mpv, with AniList tracking"
  homepage "https://github.com/EmoFa/tsuzuki"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "tsuzuki"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsuzuki"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Anikoto and bot-protection checks need Chrome or Chromium.
    Run `tsuzuki doctor` to check your setup.
  EOS
end
