# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsuzuki" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "7774e5808d5a13d1dc8d807c17d7de56ee588672c2ba94f909a9b7adfd99fc46"
      url "https://github.com/EmoFa/tsuzuki/releases/download/v#{version}/tsuzuki_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "32e2ffb47eefc6880c4f9b9ead437aabec2ced460cb503a3f5dac22cd2874555"
      url "https://github.com/EmoFa/tsuzuki/releases/download/v#{version}/tsuzuki_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1df03831182bdafa7e079f2931e2b2934f72cc53438e22d1e380f00755226a3c"
      url "https://github.com/EmoFa/tsuzuki/releases/download/v#{version}/tsuzuki_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1b08c41ee5ae631c2d6e8d4a95dda22ba25f66dd5c7a4e983520731945631883"
      url "https://github.com/EmoFa/tsuzuki/releases/download/v#{version}/tsuzuki_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tsuzuki"
  desc "Watch anime from your terminal in mpv, with AniList tracking"
  homepage "https://github.com/EmoFa/tsuzuki"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "tsuzuki"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsuzuki"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Anikoto and bot-protection checks need Chrome or Chromium.
    Run `tsuzuki doctor` to check your setup.
  EOS
end
